# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6dd29024c223d1313433a83c541d2cc3"
name = "vowelapp"
handle = "vowelapp-1"
application_url = "https://triangle-loading-malta-pulling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingapp-vowel-web.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://triangle-loading-malta-pulling.trycloudflare.com/auth/callback",
  "https://triangle-loading-malta-pulling.trycloudflare.com/auth/shopify/callback",
  "https://triangle-loading-malta-pulling.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
